# Default values for public-suggestions-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
eksCluster: false
replicaCount: 2
image:
  repository: coco/public-suggestions-api
  version: "" # should be set explicitly at installation
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 64Mi
  limits:
    memory: 256Mi
env:
  AUTHORS_SUGGESTION_API_BASE_URL: "" # This should be defined in the specific app-configs folder
  AUTHORS_SUGGESTION_ENDPOINT: "" # This should be defined in the specific app-configs folder
  ONTOTEXT_SUGGESTION_API_BASE_URL: "" # This should be defined in the specific app-configs folder
  ONTOTEXT_SUGGESTION_ENDPOINT: "" # This should be defined in the specific app-configs folder
  PUBLIC_THINGS_API_BASE_URL: "" # This should be defined in the specific app-configs folder
  PUBLIC_THINGS_ENDPOINT: "" # This should be defined in the specific app-configs folder
  CONCEPT_BLACKLISTER_BASE_URL: "" # This should be defined in the specific app-configs folder
  CONCEPT_BLACKLISTER_ENDPOINT: "" # This should be defined in the specific app-configs folder
  LOG_LEVEL: "info"
